version: 2.1

jobs:
  build:
    environment:
      IMAGE_NAME: quay.io/fitraalim/rest-template
    docker:
      - image: circleci/openjdk:11-jdk-buster
    working_directory: ~/rest-template
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Maven Dependency
          command:  mvn dependency:go-offline
      - run:
          name: Maven Build
          command:  mvn clean package
      - run:
          name: Push Container Image
          command: |
            docker build -t $IMAGE_NAME:latest .
            docker login -u $QUAY_LOGIN -p $QUAY_PWD quay.io
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-main:
    jobs:
      - build:
          context: quay-context
          filters:
            branches:
              only:
                - main
