version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: fitraalim/spring-boot-rest-template-example
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-main:
    jobs:
      - build:
          context: docker-context
          filters:
            branches:
              only: main
